export interface IObject {
  address: string;
  advanseDeposit: number;
  agentComission: number;
  cadastralNumber: string;
  city: string;
  cloudLink: string;
  companies: Company[];
  contacts: Contact[];
  created_at: string;
  currentRenters: string;
  district: string;
  electricityKw: number;
  estateTypes: string;
  fullDescription: string;
  identifier: string;
  indexingAnnual: number;
  latitude: number;
  loadingArea: string;
  longitude: number;
  metro: string;
  objectConditions: string;
  objectProperties: string;
  objectTypes: string;
  parkingQuantity: number;
  premisesFloor: string;
  premisesHeight: number;
  rentPrice: number;
  rentSquare: number;
  rentTypes: string;
  rentalHolidays: string;
  securityDeposit: number;
  status: string;
  tradeArea: string;
  updated_at: string;
  userId: string;
  waterSuply: string;
  zoom: number;
  _id: string;
}

type Contact = { contact: string };
type Company = { company: string };
