export interface IObject {
  address: string;
  advanseDeposit: number;
  agentComission: number;
  cadastralNumber: string;
  city: string;
  cloudLink: string;
  companies: CompanyType[];
  contacts: ContactType[];
  created_at: string;
  currentRenters: string;
  district: string;
  electricityKw: number;
  estateTypes: string;
  fullDescription: string;
  identifier: string;
  indexingAnnual: number;
  latitude: number;
  loadingArea: string;
  longitude: number;
  metro: string;
  objectConditions: string;
  objectProperties: string;
  objectTypes: string;
  parkingQuantity: number;
  premisesFloor: string;
  premisesHeight: number;
  rentPrice: number;
  rentSquare: number;
  rentTypes: string;
  rentalHolidays: string;
  securityDeposit: number;
  status: string;
  tradeArea: string;
  updated_at: string;
  userId: string;
  waterSuply: string;
  zoom: number;
  _id: string;
}

export interface IObjectCreateInitState {
  status: string;
  contact: string;
  fullDescription: string;
  city: string;
  address: string;
  district: string;
  metro: string;
  identifier: string;
  rentPrice: string;
  securityDeposit: string;
  advanseDeposit: string;
  agentComission: string;
  rentSquare: string;
  rentalHolidays: string;
  indexingAnnual: string;
  rentTypes: string;
  currentRenters: string;
  objectConditions: string;
  estateTypes: string;
  objectTypes: string;
  tradeArea: string;
  premisesHeight: string;
  premisesFloor: string;
  parkingQuantity: string;
  electricityKw: string;
  waterSuply: string;
  cadastralNumber: string;
  loadingArea: string;
  objectProperties: string;
  cloudLink: string;
}

export type ContactType = { contact: string };
export type CompanyType = { company: string };
