export interface IDialogPagesState {
  createPage: boolean;
  updatePage: boolean;
  objectPage: boolean;
  updateObjectPage: boolean;
  createPresentationPage: boolean;
  updatePresentationPage: boolean;
  videoPlayerPage: boolean;
  objectId: string | null;
  userId: string | null;
  contactId: string;
  presentationId: string;
  dateCreate: string | Date | null;
  createMyTaskPage: boolean;
  updateMyTaskPage: boolean;
  createManagerTaskPage: boolean;
  updateManagerTaskPage: boolean;
  createLastContactPage: boolean;
  updateLastContactPage: boolean;
  createMeetingPage: boolean;
  updateMeetingPage: boolean;
  taskId: string;
  lastContactId: string;
  meetingId: string;
  transferObjectPage: boolean;
  createCompanyPage: boolean;
  updateCompanyPage: boolean;
  loginPage: boolean;
  agreementPage: boolean;
  registerPage: boolean;
  personalPolicyPage: boolean;
  createContactPage: boolean;
  openContactPage: boolean;
  companyId: string;
  createUserPage: boolean;
  updateUserPage: boolean;
  avatarUpdatePage: boolean;
  updateProfilePage: boolean;
  updatePasswordPage: boolean;
  authPage: boolean;
  startPage: boolean;
  makePaymentPage: boolean;
}
