export const objectHasDistrict = (selectedArea) => {
  return (
    selectedArea?.includes("Санкт-Петербург") ||
    selectedArea?.includes("Москва") ||
    selectedArea?.includes("Майкоп") ||
    selectedArea?.includes("Уфа") ||
    selectedArea?.includes("Улан-Удэ") ||
    selectedArea?.includes("Горно-Алтайск") ||
    selectedArea?.includes("Махачкала") ||
    selectedArea?.includes("Нальчик") ||
    selectedArea?.includes("Элиста") ||
    selectedArea?.includes("Черкесск") ||
    selectedArea?.includes("Петрозаводск") ||
    selectedArea?.includes("Сыктывкар") ||
    selectedArea?.includes("Симферополь") ||
    selectedArea?.includes("Йошкар-Ола") ||
    selectedArea?.includes("Саранск") ||
    selectedArea?.includes("Якутск") ||
    selectedArea?.includes("Владикавказ") ||
    selectedArea?.includes("Казань") ||
    selectedArea?.includes("Кызыл") ||
    selectedArea?.includes("Ижевск") ||
    selectedArea?.includes("Абакан") ||
    selectedArea?.includes("Грозный") ||
    selectedArea?.includes("Чебоксары") ||
    selectedArea?.includes("Барнаул") ||
    selectedArea?.includes("Чита") ||
    selectedArea?.includes("Петропавловск-Камчатский") ||
    selectedArea?.includes("Краснодар") ||
    selectedArea?.includes("Красноярск") ||
    selectedArea?.includes("Пермь") ||
    selectedArea?.includes("Владивосток") ||
    selectedArea?.includes("Ставрополь") ||
    selectedArea?.includes("Хабаровск") ||
    selectedArea?.includes("Благовещенск") ||
    selectedArea?.includes("Архангельск") ||
    selectedArea?.includes("Астрахань") ||
    selectedArea?.includes("Белгород") ||
    selectedArea?.includes("Брянск") ||
    selectedArea?.includes("Владимир") ||
    selectedArea?.includes("Волгоград") ||
    selectedArea?.includes("Вологда") ||
    selectedArea?.includes("Воронеж") ||
    selectedArea?.includes("Иваново") ||
    selectedArea?.includes("Иркутск") ||
    selectedArea?.includes("Калининград") ||
    selectedArea?.includes("Калуга") ||
    selectedArea?.includes("Кемерово") ||
    selectedArea?.includes("Киров") ||
    selectedArea?.includes("Кострома") ||
    selectedArea?.includes("Курган") ||
    selectedArea?.includes("Курск") ||
    selectedArea?.includes("Липецк") ||
    selectedArea?.includes("Магадан") ||
    selectedArea?.includes("Красногорск") ||
    selectedArea?.includes("Мурманск") ||
    selectedArea?.includes("Нижний Новгород") ||
    selectedArea?.includes("Великий Новгород") ||
    selectedArea?.includes("Новосибирск") ||
    selectedArea?.includes("Омск") ||
    selectedArea?.includes("Оренбург") ||
    selectedArea?.includes("Орёл") ||
    selectedArea?.includes("Пенза") ||
    selectedArea?.includes("Псков") ||
    selectedArea?.includes("Ростов-на-Дону") ||
    selectedArea?.includes("Рязань") ||
    selectedArea?.includes("Самара") ||
    selectedArea?.includes("Саратов") ||
    selectedArea?.includes("Южно-Сахалинск") ||
    selectedArea?.includes("Екатеринбург") ||
    selectedArea?.includes("Смоленск") ||
    selectedArea?.includes("Тамбов") ||
    selectedArea?.includes("Тверь")
  );
};
